### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by FatGrandpa007** [BlackWolfsDen/Justicar-WoW#1]
So I'm having an issue compiling, would be really great if you could help me out real quick, I've been trying to get in contact with you for awhile but can't find any contact info anywhere at all.

I'd be really happy if I could get in contact with you real quick, I'd pay for the help as well.

**Comment by BlackWolfsDen** [comment]
i had no hands in the creation of this repo . i just grabbed a clone of the original repo when it was public but never even tried to compile it lol

**Comment by DearAdmin** [comment]
where is world database sql  ? :o
